export const questionsWithCorrectIndex = {
  id: "41f10b5b-6f6a-4e76-a266-59b069870eff",
  title: "New Test",
  type: "reading",
  description: "",
  sections: [
    {
      id: "7fb5b6e6-06c4-4433-9391-48dc1d0b4309",
      title: "Section 1",
      description: "",
      questions: [
        {
          id: "10c69f5d-050c-433d-a477-26ea73544e4e",
          type: "multiple-choice",
          text: "x,cmnbshlfjghs",
          points: 1,
          scoringStrategy: "all-or-nothing",
          options: ["o94837598234", ".,mxnvbxvb", "134134", "fsgsdfgsdfg"],
          correctAnswer: 0,
          index: 1,
          partialEndingIndex: 1,
        },
        {
          id: "e484d924-6ac9-49e8-acc5-3c516a8fdb32",
          type: "matching",
          text: "xcvb.,mklgjhldf",
          points: 1,
          scoringStrategy: "partial",
          items: ["134", "sfgsfg", "xvcb"],
          options: ["xcbnvn", "fghjfghj", "jkhjkhjk"],
          correctMatches: {
            "0": 0,
            "1": 1,
            "2": 2,
          },
          index: 2,
          partialEndingIndex: 4,
          subQuestions: [
            {
              subIndex: 2,
              subId: "e484d924-6ac9-49e8-acc5-3c516a8fdb32_sub1",
              itemContent: "134",
              correctAnswer: "xcbnvn",
            },
            {
              subIndex: 3,
              subId: "e484d924-6ac9-49e8-acc5-3c516a8fdb32_sub2",
              itemContent: "sfgsfg",
              correctAnswer: "fghjfghj",
            },
            {
              subIndex: 4,
              subId: "e484d924-6ac9-49e8-acc5-3c516a8fdb32_sub3",
              itemContent: "xvcb",
              correctAnswer: "jkhjkhjk",
            },
          ],
        },
        {
          id: "c50a51a2-3c6d-4a97-8d6a-3f388e7f625b",
          type: "true-false-not-given",
          text: "b,mcnb,.cv.bn",
          points: 1,
          scoringStrategy: "partial",
          statements: [
            ".dklgjhoweiuty",
            ";liqytoiyhekjfnv",
            "x.,nvbshdfg",
            "1341234",
          ],
          correctAnswers: ["true", "true", "false", "not-given"],
          index: 5,
          partialEndingIndex: 8,
          subQuestions: [
            {
              subIndex: 5,
              subId: "c50a51a2-3c6d-4a97-8d6a-3f388e7f625b_sub1",
              itemContent: ".dklgjhoweiuty",
              correctAnswer: "true",
            },
            {
              subIndex: 6,
              subId: "c50a51a2-3c6d-4a97-8d6a-3f388e7f625b_sub2",
              itemContent: ";liqytoiyhekjfnv",
              correctAnswer: "true",
            },
            {
              subIndex: 7,
              subId: "c50a51a2-3c6d-4a97-8d6a-3f388e7f625b_sub3",
              itemContent: "x.,nvbshdfg",
              correctAnswer: "false",
            },
            {
              subIndex: 8,
              subId: "c50a51a2-3c6d-4a97-8d6a-3f388e7f625b_sub4",
              itemContent: "1341234",
              correctAnswer: "not-given",
            },
          ],
        },
        {
          id: "a48cbb01-be46-43b0-82f3-800bcf26c656",
          type: "short-answer",
          text: "x,cmvnbsdfhgoiwre",
          points: 1,
          scoringStrategy: "partial",
          questions: ["1234134", "qwetwrt"],
          correctAnswers: [
            ["xbvxb", "xcvb", "xvcb"],
            ["xcvncvbn", "xcvbcv"],
          ],
          wordLimit: 3,
          index: 9,
          partialEndingIndex: 10,
          subQuestions: [
            {
              subIndex: 9,
              subId: "a48cbb01-be46-43b0-82f3-800bcf26c656_sub1",
              itemContent: "1234134",
              correctAnswer: ["xbvxb", "xcvb", "xvcb"],
            },
            {
              subIndex: 10,
              subId: "a48cbb01-be46-43b0-82f3-800bcf26c656_sub2",
              itemContent: "qwetwrt",
              correctAnswer: ["xcvncvbn", "xcvbcv"],
            },
          ],
        },
      ],
      duration: 600,
      readingPassage: {
        id: "339e4820-e9b9-4b83-9224-56348c97d455",
        title: "testadf",
        content: "as.jdhflakhdfladjsflkadf",
        hasImages: false,
        imageUrls: [],
      },
    },
    {
      id: "bb1b915e-fa32-473e-b44c-74cb79ef2b9e",
      title: "Section 2",
      description: "",
      questions: [
        {
          id: "df6dcbf8-57d0-4f22-9f69-f847fe063760",
          type: "completion",
          text: ",xmcnbvm,xvnmbxvb",
          points: 1,
          scoringStrategy: "partial",
          blanks: 2,
          correctAnswers: ["xvbxcvb", "2141324"],
          index: 11,
          partialEndingIndex: 12,
          subQuestions: [
            {
              subIndex: 11,
              subId: "df6dcbf8-57d0-4f22-9f69-f847fe063760_sub1",
              itemContent: "Blank 1",
              correctAnswer: "xvbxcvb",
            },
            {
              subIndex: 12,
              subId: "df6dcbf8-57d0-4f22-9f69-f847fe063760_sub2",
              itemContent: "Blank 2",
              correctAnswer: "2141324",
            },
          ],
        },
        {
          id: "f314586e-a552-4a5e-8add-18fe0a1dfdf8",
          type: "pick-from-list",
          text: "cx.,mnbhskjlfg",
          points: 1,
          scoringStrategy: "partial",
          items: ["ouyoiwert", "sbxbvxcvbx"],
          options: ["qleroiqeur", "woirutowiret", "sldfhgslkdfg"],
          correctAnswers: {
            "0": 0,
            "1": 1,
          },
          index: 13,
          partialEndingIndex: 14,
          subQuestions: [
            {
              subIndex: 13,
              subId: "f314586e-a552-4a5e-8add-18fe0a1dfdf8_sub1",
              itemContent: "ouyoiwert",
              correctAnswer: "qleroiqeur",
            },
            {
              subIndex: 14,
              subId: "f314586e-a552-4a5e-8add-18fe0a1dfdf8_sub2",
              itemContent: "sbxbvxcvbx",
              correctAnswer: "woirutowiret",
            },
          ],
        },
        {
          id: "81086855-951b-4bbd-9d45-d4e8f942b042",
          type: "matching-headings",
          text: "lkajhdflhalsdfadsf",
          points: 1,
          scoringStrategy: "partial",
          paragraphs: ["asdfadsf", "asdfasdfcv", "zxcv"],
          headings: ["fhdfgghfdg", "asdfadsf", "vbncvbn"],
          correctMatches: {
            "0": 0,
            "1": 1,
            "2": 0,
          },
          index: 15,
          partialEndingIndex: 17,
          subQuestions: [
            {
              subIndex: 15,
              subId: "81086855-951b-4bbd-9d45-d4e8f942b042_sub1",
              itemContent: "asdfadsf",
              correctAnswer: "fhdfgghfdg",
            },
            {
              subIndex: 16,
              subId: "81086855-951b-4bbd-9d45-d4e8f942b042_sub2",
              itemContent: "asdfasdfcv",
              correctAnswer: "asdfadsf",
            },
            {
              subIndex: 17,
              subId: "81086855-951b-4bbd-9d45-d4e8f942b042_sub3",
              itemContent: "zxcv",
              correctAnswer: "fhdfgghfdg",
            },
          ],
        },
      ],
      duration: 600,
      readingPassage: {
        id: "11a96e75-42e8-4ae7-8dc1-ce669b1f2bab",
        title: "a.sdklfjaoidf",
        content: "xncvblahfgoiuqhrt",
        hasImages: false,
        imageUrls: [],
      },
    },
  ],
  totalDuration: 1200,
  totalQuestions: 7,
  instructions:
    "You should spend about 20 minutes on each section. Read the passages and answer the questions. There is no extra time to transfer your answers, so write your answers directly on the answer sheet.",
};
